name: The second site
favicon: null
layout_spectrum: 0.4289720728993416
typography_spectrum: 0.7334755219053477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9033690041396767
  lightness: 0.41304248850792646
  saturation: 0.7347545332740992
  rhythmicContrast: 0.04131238185800612
purpose: []
